# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qmlclock

# >> macros
# << macros

Summary:    QML clocks application
Version:    0.0.6
Release:    1
Group:      Applications/System
License:    BSD
URL:        http://github.com/nemomobile/qmlclock
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlclock.yaml
Requires:   nemo-qml-plugin-time-qt5
Requires:   nemo-qml-plugin-alarms-qt5
Requires:   qt-components-qt5
Requires:   mapplauncherd-booster-qtcomponents-qt5
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  mapplauncherd-qt5 >= 1.1.0
BuildRequires:  desktop-file-utils

%description
Clocks application written using QML


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/qmlclock
%{_datadir}/applications/qmlclock.desktop
# >> files
# << files
